[package]
name = "rusxr_tests"
version = "0.1.0"
authors = ["gkhk <gkhk.zu@gmail.com>"]
edition = "2021"
publish = false
repository = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsx = { path = "../rsx" }
